config/routes.rb
Rails.application.routes.draw do

  root 'admin#home'

  get 'articulos', to: 'articulos#index', as: 'articulos'
  get 'articulos/new', to: 'articulos#new', as: 'new_articulos'
  get 'articulo/:id', to: 'articulos#show', as: 'articulo'
  get 'articulo/:id/edit', to: 'articulos#edit', as: 'edit_articulo'
  post 'articulos', to: 'articulos#create', as: 'create_articulo'
  patch 'articulos/:id', to: 'articulos#update', as: 'update_articulo'
  delete 'articulo/:id', to: 'articulos#destroy', as: 'delete_articulo'

  get 'categorias', to: 'categorias#index', as: 'categorias'
  get 'categorias/new', to:'categorias#new', as: 'new_categoria'
  post 'categorias', to: 'categorias#create', as: 'create_categoria'
  delete 'categorias/:id', to: 'categorias#destroy', as: 'delete_categoria'

  get 'categorias/:categoria_id/articulos', to: 'articulos#index', as: 'categoria_articulos'
  get 'categorias/:categoria_id/articulos/new', to: 'articulos#new', as: 'new_categoria_articulos'

  get 'admin/sql', to: 'admin#sql', as: 'sql'
  post 'admin/sql', to: 'admin#execute_sql', as: 'execute_sql'

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base

  has_and_belongs_to_many :categorias

  def texto=(texto)
    article_manager = ArticleManager.new titulo
    article_manager.write texto
    self.url = article_manager.url
  end

  def texto
    return nil if new_record?
    article_manager = ArticleManager.new titulo
    article_manager.read
  end

  def self.paginate(data)
    if dv(data[:q])
      qs = data[:qs]
      qs = 'titulo' if !dv(qs)
      query = where(qs => data[:q])
    else
      query = all
    end
    if dv(data[:o])
      query = query.order(data[:o])
    end
    return query.all
  end

  def self.dv (data)
    return !((data == nil) || (data == '') || (data == ' '))
  end

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  self.table_name = 'categorias'

  has_and_belongs_to_many :articulos

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def home
  end

  def sql
    render layout: nil
  end

  def execute_sql
    results = ActiveRecord::Base.connection.exec_query(params[:comando])
    text = "<tr>"
    results.columns.each do |c|
      text += "<th>#{c}</th>"
    end
    text += "</tr>"
    results.rows.each do |r|
      text += "<tr>"
      r.each do |d|
        text += "<td>#{d}</td>"
      end
      text += "</tr>"
    end
    render text: "<table>#{text}</table>"
    return
  rescue Exception => e
    render text: e.message
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController

  def index
    if params[:categoria_id] == nil
      @categoria = nil
      @articulos = Articulo.paginate params
    else
      @categoria = Categoria.find params[:categoria_id]
      @articulos = @categoria.articulos
    end
  end

  def show
    @articulo = Articulo.find params[:id]
  end

  def new
    @articulo = Articulo.new
    @path = create_articulo_path
  end

  def edit
    @articulo = Articulo.find params[:id]
    @path = update_articulo_path(@articulo)
  end

  def create
    @articulo = Articulo.new params_articulos
    @categorias = params[:articulo][:categorias]
    @categorias = {} if @categorias == nil
    @categorias.each do |key, value|
      categoria = Categoria.find value
      @articulo.categorias << categoria
    end
    @articulo.save
    redirect_to articulos_path
  end

  def update
    @articulo = Articulo.find params[:id]
    @articulo.update params_articulos
    redirect_to articulos_path
  end

  def destroy
    @articulo = Articulo.find params[:id]
    @articulo.delete
    redirect_to articulos_path
  end

  private
    def params_articulos
      params[:articulo].clone.permit!.delete_if{|key, value| key == 'categorias'}
    end 

end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController

  def index
    @categorias = Categoria.all
  end

  def new
    @categoria = Categoria.new
  end

  def create
    params.permit!
    @categoria = Categoria.new params[:categoria]
    @categoria.save
    redirect_to categorias_path
  end

  def destroy
    @categoria = Categoria.find params[:id]
    if @categoria.articulos.count == 0
      @categoria.delete
      flash[:notice] = "Categoria eliminada con éxito!"
    else
      flash[:alert] = "No se pueden eliminar categorias con articulos"
    end
    redirect_to categorias_path
  end

  def link_empty
    link_to 'Link Vacio', '#'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
  def format_html(texto)
    texto.gsub(/\n/, '<br>').html_safe
  end
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/views/admin/home.html.erb
<h1>Super Blog de Arnaud</h1>

app/views/admin/sql.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <title>SQL Console</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <style type="text/css">
    body {
      background: #222;
      color: #3e3;
      font-family: monospace;
      cursor: default;
    }
    #lastChar {
      text-decoration: underline;
      white-space: pre-wrap;
    }
    #textPart::-moz-selection,
    #nextPart::-moz-selection {
      background: #fff;
      color: #191;
    }
  </style>
  <script type="text/javascript">
    var lastChar;
    var textPart;
    var nextPart;
    var lastLines = [];
    var lastSearchNumber = 0;

    $().ready( function () {
      $('body').keypress(key);
      $('body').keydown(down);
      textPart = $('#textPart');
      lastChar = $('#lastChar');
      nextPart = $('#nextPart');
    });

    function key (e) {
      var text = textPart.html();
      var nchar = String.fromCharCode(e.which);
      //tecla enter
      if (e.which == 13) {
        send();
      }
      //tecla borrar
      else if (e.which == 8) {
        var l = text.length;
        if (text.substring(l-4, l) != '<br>') {
          textPart.html(text.substring(0, l-1));
        }
      }
      //tecla espacio
      else if (e.which == 32) {
        var tl = text.length;
        var nextChar = nextPart.html().substring(0,1);
        var prevChar = text.substring(tl-1,tl);
        var sp = " ";
        if (
          (
            prevChar != sp &&
            lastChar.html() != sp
          ) || (
            nextChar == '' &&
            prevChar != ' '
          )
          ){
          textPart.html(text + sp);
        }
      }
      else {
        textPart.html(text + nchar);
      }
    }

    function down (e) {
      var text = textPart.html();
      var next = nextPart.html();
      //tecla izquierda
      if (e.which == 37) {
        var l = text.length;
        if (text.substring(l-4, l) != '<br>') {
          nextPart.html(lastChar.html() + next);
          lastChar.html(text.substring(l-1, l));
          textPart.html(text.substring(0,l-1));
        }
      }
      //tecla derecha
      if (e.which == 39) {
        var nextChar = next.substring(0, 1);
        var isSpace = lastChar.html() == ' ';
        if (!(isSpace && nextChar == '')) {
          textPart.html(text + lastChar.html());
          lastChar.html(next.substring(0,1));
          nextPart.html(next.substring(1,next.length));
        }
      }
      //tecla arriba
      if (e.which == 38) {
        lastSearchNumber--;
        writeLastLine();
      }
      //tecla abajo
      if (e.which == 40) {
        lastSearchNumber++;
        writeLastLine();
      }
    }

    function writeLastLine () {
      if (lastSearchNumber >= lastLines.length) {
        lastSearchNumber = lastLines.length;
      }
      else if (lastSearchNumber < 0) {
        lastSearchNumber = 0;
      } else {
        var text = textPart.html();
        var beforeText = text.substring(0, text.lastIndexOf('<br>')+4);
        nextPart.html('');
        lastChar.html(' ');
        textPart.html(beforeText + lastLines[lastSearchNumber]);
      }
    }

    function addLastLine (lastLine) {
      lastLines.push(lastLine);
      lastSearchNumber = lastLines.length;
    }

    function send () {
      var text = textPart.html() + lastChar.html() + nextPart.html();
      var lasti = text.lastIndexOf('<br>');
      var lastLine = text.substring(lasti+4, text.length);
      lastLine = lastLine.substring(0, lastLine.length - 1);

      addLastLine(lastLine);

      textPart.html(text + '<br>');
      lastChar.html(' ');
      nextPart.html('');

      if (lastLine == "exit") {
        window.location.href = "/"
      }

      var param = ($('[name="csrf-param"]').attr('content'));
      var token = ($('[name="csrf-token"]').attr('content'));
      var data = {};
      data[param] = token;
      data['comando'] = lastLine;
      var ajax = $.post('/admin/sql', data, function (data, textStatus, jqa) {
        c_ap(data);
      });
    }

    function lastText () {
      var text = textPart.html()+lastChar.text();
      var lasti = text.lastIndexOf('<br>');
      return text.substring(lasti+4, text.length);
    }

    //c_ap = console append
    function c_ap (obj) {
      var text = textPart.html();
      var val;
      if (typeof obj == "string" || obj instanceof String) {
        val = obj;
      } else {
        val = JSON.stringify(obj);
      }
      textPart.html(text + val + '<br>');
    }

  </script>
</head>
<body>
  <p id="console">
    <span id="textPart">Consola SQL<br></span
    ><span id="lastChar"> </span
    ><span id="nextPart"></span>
  </p>
</body>
</html>

app/views/articulos/_form.html.erb
<script type="text/javascript">

  var catCount = 0;

  function agregarCategoria () {
    catCount++;

    var categorias = document.getElementById('categorias');
    var categoria = document.getElementById('categoria').cloneNode(true);
    var select = categoria.getElementsByTagName('select')[0];
    select.removeAttribute('disabled');
    categoria.setAttribute('style', 'display: block;');
    categoria.setAttribute('id', 'categoria' + catCount);
    categorias.appendChild(categoria);

    var nombre = select.getAttribute('name');
    select.setAttribute('name', nombre + '[' + catCount + ']');
  }

  function quitarCategoria () {
    var categoria = document.getElementById('categoria' + catCount);
    var categorias = document.getElementById('categorias');
    categorias.removeChild(categoria);

    catCount--;
  }
</script>

<%= form_for @articulo, url: @path do |f| %>
  <%= f.text_field :titulo %>
  <%= f.label :titulo, 'Título' %> <br>
  <%= f.text_area :texto %> <br>
  <% if @articulo.new_record? %>
    <div id="categoria" style="display: none;">
      <%= f.select :categorias, 
        options_for_select(
          Categoria.all.map{ |e| [e.nombre, e.id] }
        ), {},  {disabled: true}
      %>
    </div>
    <div id="categorias">
      
    </div>
    <button type="button" onclick="agregarCategoria()">Agregar Categoria</button>
    <button type="button" onclick="quitarCategoria()">Quitar Categoria</button> <br>
  <% end %>
  <%= f.submit 'Crear', class: 'button' %>
<% end %>

app/views/articulos/edit.html.erb
<%= render 'form' %>

app/views/articulos/index.html.erb
<article>
  <h1>Articulos <%= @categoria == nil ? '' : @categoria.nombre %></h1>

  <table class="table">
    <tr>
      <th>Título</th>
      <th>Categoria</th>
      <th>Opciones</th>
    </tr>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= link_to articulo.titulo, articulo_path(articulo) %> </td>
        <td>
          <% articulo.categorias.each do |categoria| %>
            <%= categoria.nombre + ', ' %>
          <% end %>
        </td>
        <td><%= link_to "archivo", articulo.url %>
          <%= form_tag delete_articulo_path(articulo), method: 'delete' do %>
            <%= submit_tag 'Eliminar', class: 'button' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</article>
<%= form_tag request.env['PATH_INFO'], method: 'get' do %>
  <%= text_field_tag :o %> Orden <br>
  <%= text_field_tag :q %> Busqueda <br>
  <%= text_field_tag :qs %> Campo <br>
  <%= submit_tag "Buscar" %>
<% end %>

<% crear_path = @categoria == nil ? new_articulos_path : new_categoria_articulos_path %>
<%= link_to 'Nuevo Articulo', crear_path %>

app/views/articulos/new.html.erb
<%= render 'form' %>

app/views/articulos/show.html.erb
<article>
  <h1><%= @articulo.titulo %></h1>
  <p>
    <%= format_html(@articulo.texto) %>
  </p>
</article>


<p><%= link_to 'Editar', edit_articulo_path(@articulo) %></p>

app/views/categorias/index.html.erb
<article>
  <h1>Categorias</h1>
  <table>
    <tr>
      <th>Nombre</th>
      <th>Articulos</th>
      <th>Opciones</th>
    </tr>
    <% @categorias.each do |categoria| %>
      <tr>
        <td><%= link_to categoria.nombre, categoria_articulos_path(categoria) %></td>
        <td><%= categoria.articulos.count %></td>
        <td>
          <%= form_tag delete_categoria_path(categoria), method: 'delete' do %>
            <%= submit_tag 'Eliminar' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</article>
<%= link_to 'Nuevo', new_categoria_path %>

app/views/categorias/new.html.erb
<%= form_for @categoria, url: create_categoria_path do |f| %>
  <%= f.text_field :nombre %>
  <%= f.label :nombre, 'Nombre' %>
  <br>
  <%= f.submit 'Aceptar' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <style type="text/css">

    div, nav, article, section {
      /*border: 1px solid #eee;
      /*margin: 5px;
      padding: 10px;*/
      display: block;
    }

    a:link, a:visited {
      color: #57b;
      text-decoration: none;
    }
    a:hover, a:active {
      color: #24b;
      text-decoration: underline;
    }
    table, tr, th, td {
      border: 1px inset #aaa;
      border-radius: 10px;
    }
    body {
      font-family: sans-serif;
      color: #444;
    }
    button, input[type="submit"], select {
      padding:2px;
      background: linear-gradient(to bottom,#f7f7f7,#f0f0f0);
      border: 1px outset #ddd;
      border-radius: 2px;
    }
    button:hover, input[type="submit"]:hover, select:hover {
      background: linear-gradient(to bottom,#eee,#ddd);
    }
    input, textarea {
      background-color: #fafafa;
      border: 1px inset #999;
      border-radius: 2px;
    }
    table {
      background: linear-gradient(to bottom right, #f0f5ff, #cef);
    }
    td, th {
      box-shadow: 0 0 4px #68b inset;
    }

    /* -- Menus -- */
    .menu {
      padding: 0px;
      margin: 0px;
      overflow: hidden;
      text-align: center;
    }
    .menu > li {
      float: left;
      list-style-type: none;
      padding: 0px;
      margin: 0px;
    }
    .menu > li > ul {
      display: none;
      padding: 0px;
      margin: 0px;
      position: absolute;
    }
    .menu > li:hover > ul{
      display: block;
      list-style-type: none;
    }

    .menu > li > ul > li {
      display: block;
    }
    .menu a {
      background: linear-gradient(to bottom right, #bdf, #acf, #9bf);
      padding: 0px;
      display: block;
      box-shadow: inset 0 0 10px -2px #68b;
      width: 120px;
      height: 30px;
      line-height: 30px;
      color: #449;
      text-decoration: none;
      border-radius: 5px;
      border: 2px solid #68b;
    }
    .menu a:hover {
      box-shadow: inset 0 0 10px #fff;
    }

  </style>
</head>
<body>
<nav>
  <ul class="menu">
    <li>
      <%= link_to 'Articulos' , articulos_path  %>
      <ul>
        <li><%= link_to 'Lista', articulos_path %></li>
        <li><%= link_to 'Categorias', categorias_path %></li>
        <li><%= link_to 'Nuevo', new_articulos_path %></li>
      </ul>
    </li>
    <li>
      <%= link_to 'Admin', '#' %>
      <ul>
        <li><%= link_to 'SQL', sql_path %></li>
      </ul>
    </li>
  </ul>
</nav>
<% if flash.any? %>
  <ul class="flash">
    <% flash.each do |name, message| %>
      <li class="<%= name %>"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<section>
<%= yield %>
</section>

</body>
</html>